#!/bin/sh

riverctl map normal Super R spawn "riverbedctl"

riverctl map normal Super Return spawn konsole
riverctl map normal Super Space spawn 'tofi-drun | xargs riverctl spawn'
riverctl map normal Super+Shift Space spawn 'echo | tofi | sh'

riverctl map normal Super+Shift q close
riverctl map normal Super+Shift Return zoom

riverctl map normal Super+Shift Down swap next
riverctl map normal Super+Shift Up swap previous

riverctl map normal Super Down focus-view next
riverctl map normal Super Up focus-view previous

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

riverctl map normal Super F send-layout-cmd luatile 'toggle_maximize()'
riverctl map normal Super+Alt F toggle-fullscreen
riverctl map normal Super+Shift f toggle-float

riverctl map normal None Print spawn 'grimshot save area ~/Pictures/Screenshots/$(date +%d-%m-%y-%H:%M).png'
riverctl map normal None XF86Sleep spawn 'gtklock'

riverctl map normal Super P spawn "ls $HOME/.password-store | cut -d. -f1 | tofi | xargs pass otp | xargs wtype"

wobBrightness="-m | cut -d, -f4 | sed 's/%//g' > $XDG_RUNTIME_DIR/wob/brightness"
wobVolume="&& pactl get-sink-volume @DEFAULT_SINK@ | grep -m 1 -o '[0-9][0-9]*%' | grep -m 1 -o '[0-9][0-9]*' > $XDG_RUNTIME_DIR/wob/volume"

for mode in normal locked
do
	riverctl map -repeat $mode None XF86MonBrightnessUp 	spawn "brightnessctl set +1% $wobBrightness"
	riverctl map -repeat $mode None XF86MonBrightnessDown 	spawn "brightnessctl set 1%- $wobBrightness"
	riverctl map -repeat $mode Shift XF86MonBrightnessUp 	spawn "brightnessctl set +5% $wobBrightness"
	riverctl map -repeat $mode Shift XF86MonBrightnessDown 	spawn "brightnessctl set 5%- $wobBrightness"

	riverctl map -repeat $mode None XF86AudioRaiseVolume 	spawn "pactl set-sink-volume @DEFAULT_SINK@ +1% $wobVolume"
	riverctl map -repeat $mode None XF86AudioLowerVolume 	spawn "pactl set-sink-volume @DEFAULT_SINK@ -1% $wobVolume"
	riverctl map -repeat $mode Shift XF86AudioRaiseVolume 	spawn "pactl set-sink-volume @DEFAULT_SINK@ +5% $wobVolume"
	riverctl map -repeat $mode Shift  XF86AudioLowerVolume 	spawn "pactl set-sink-volume @DEFAULT_SINK@ -5% $wobVolume"
	riverctl map -repeat $mode None XF86AudioMute 			spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'
done


for i in $(seq 1 9)
do
	tags=$((1 << ($i -1)))
	riverctl map normal Super $i set-focused-tags $tags
	riverctl map normal Super+Shift $i set-view-tags $tags

    riverctl map normal Super+Control $i toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags
