#!/bin/sh

if ! command -v systemctl 2>&1 >/dev/null
then
	export XDG_CURRENT_DESKTOP=lxqt

	export QT_QPA_PLATFORM=wayland
	export QT_QPA_PLATFORMTHEME=xdgdesktopportal
	export QT_STYLE_OVERRIDE=kvantum

	export XDG_RUNTIME_DIR=$(mkrundir)

	ck-launch-session dbus-launch --sh-syntax --exit-with-session seatd-launch -- river
else
	dbus-launch --sh-syntax --exit-with-session river
fi
