#!/bin/sh

killall waybar

height=$(cat "$HOME/.config/waybar/config.jsonc" | grep height | grep -o '[0-9][0-9]*')

riverctl send-layout-cmd luatile "set_bar_height(48)"
waybar
riverctl send-layout-cmd luatile 'set_bar_height(0)'
